plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

collections:
  projects:
    output: true

gems:
  - jekyll-paginate-v2

domain: arads7420.github.io # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://arads7420.github.io # the base hostname and protocol for your site, e.g. http://example.com
baseurl: /arads7420.github.io/ # place folder name if the site is served in a subfolder
